package pl.pwr.ite.bedrylo.ui;

import pl.pwr.ite.bedrylo.data.AvailableStock;
import pl.pwr.ite.bedrylo.data.MatchList;
import pl.pwr.ite.bedrylo.data.PreferenceList;
import pl.pwr.ite.bedrylo.logic.Evolution;
import pl.pwr.ite.bedrylo.misc.ConfigClass;
import pl.pwr.ite.bedrylo.misc.FileHandler;

import javax.swing.*;
import java.awt.*;

public class InitialScreen extends JFrame {

    private final SpinnerNumberModel generationSpinnerModel = new SpinnerNumberModel(100, 1, 10000, 1);
    private final SpinnerNumberModel matchListSpinnerModel = new SpinnerNumberModel(10, 1, 200, 1);
    private final SpinnerNumberModel comparisonSpinnerModel = new SpinnerNumberModel(5, 1, 100, 1);
    private JPanel panel1;
    private JButton preferenceButton;
    private JButton stockButton;
    private JButton discountButton;
    private JButton startButton;
    private JSpinner generationCountSpinner;
    private JSpinner matchListCountSpinner;
    private JSpinner comparisonCountSpinner;
    private JLabel preferencePathLabel;
    private JLabel stockPathLabel;
    private JLabel dicountPathLabel;
    private JLabel generationCountLabel;
    private JLabel matchListCountLabel;
    private JLabel comparisonAmountLabel;
    private JLabel startButtonLabel;
    private JLabel warning;
    private JLabel errorLabel;

    public InitialScreen() {
        super("Dopasowywanie nart");
        $$$setupUI$$$();
        setContentPane(panel1);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(800, 600));
        pack();
        setVisible(true);
        preferenceButton.addActionListener(e -> {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showOpenDialog(panel1);
            ConfigClass.setPreferencesListPath(fileChooser.getSelectedFile().getAbsolutePath());
            preferencePathLabel.setText("Wybrano plik preferencji");
        });
        stockButton.addActionListener(e -> {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showOpenDialog(panel1);
            ConfigClass.setSkiListPath(fileChooser.getSelectedFile().getAbsolutePath());
            stockPathLabel.setText("Wybrano plik nart");
        });
        discountButton.addActionListener(e -> {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showOpenDialog(panel1);
            ConfigClass.setDiscountsListPath(fileChooser.getSelectedFile().getAbsolutePath());
            dicountPathLabel.setText("Wybrano plik rabatów");
        });
        startButton.addActionListener(e -> {
            setTitle("Pracuję nad dopasowaniem nart");
            startButton.setEnabled(false);
            ConfigClass.setGenerationMaxNumber((Integer) generationCountSpinner.getValue());
            ConfigClass.setMatchListCount((Integer) matchListCountSpinner.getValue());
            ConfigClass.setComparisonAmount((Integer) comparisonCountSpinner.getValue());
            try {
                AvailableStock availableStock = new AvailableStock(FileHandler.readSkiList(ConfigClass.getSkiListPath()));
                FileHandler.readDiscountList(ConfigClass.getDiscountsListPath());
                FileHandler.readPreferenceList(ConfigClass.getPreferencesListPath());
                PreferenceList.sortByDiscountAscending();
                errorLabel.setText("");
                warning.setText("Pracuję nad dopasowaniem nart");
                MatchList bestMatchList = Evolution.evolve(availableStock, ConfigClass.getGenerationMaxNumber(), ConfigClass.getMatchListCount(), ConfigClass.getComparisonAmount());
                StringBuilder resultString = new StringBuilder();
                resultString.append(bestMatchList.toString()).append("\n\n");
                for (var match : bestMatchList.getMatches()) {
                    resultString.append(match.toString()).append("\n");
                }
                setVisible(false);
                new EvolutionScreen(resultString.toString(), bestMatchList);
            } catch (Exception exception) {
                warning.setText("Wystąpił błąd, sprawdź wprowadzone dane wejściowe i spróbuj ponownie");
                errorLabel.setText(exception.getMessage());
                startButton.setEnabled(true);
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(9, 2, new Insets(0, 0, 0, 0), -1, -1));
        preferencePathLabel = new JLabel();
        preferencePathLabel.setText("Wybierz plik preferencji");
        panel1.add(preferencePathLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stockPathLabel = new JLabel();
        stockPathLabel.setText("Wybierz plik nart");
        panel1.add(stockPathLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dicountPathLabel = new JLabel();
        dicountPathLabel.setText("Wybierz Plik Rabatów");
        panel1.add(dicountPathLabel, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generationCountLabel = new JLabel();
        generationCountLabel.setText("Ile maksymalnie tur");
        panel1.add(generationCountLabel, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        matchListCountLabel = new JLabel();
        matchListCountLabel.setText("Ile list na ture");
        panel1.add(matchListCountLabel, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comparisonAmountLabel = new JLabel();
        comparisonAmountLabel.setText("Ile porównań na narciarza");
        panel1.add(comparisonAmountLabel, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        preferenceButton = new JButton();
        preferenceButton.setText("otwórz");
        panel1.add(preferenceButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stockButton = new JButton();
        stockButton.setText("otwórz");
        panel1.add(stockButton, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        discountButton = new JButton();
        discountButton.setText("otwórz");
        panel1.add(discountButton, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        startButtonLabel = new JLabel();
        startButtonLabel.setText("Start");
        panel1.add(startButtonLabel, new com.intellij.uiDesigner.core.GridConstraints(8, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        startButton = new JButton();
        startButton.setText("Start");
        panel1.add(startButton, new com.intellij.uiDesigner.core.GridConstraints(8, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(generationCountSpinner, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(matchListCountSpinner, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(comparisonCountSpinner, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        warning = new JLabel();
        warning.setText("UWAGA PROGRAM NIE SPRAWDZA POPRAWNOŚCI WPROWADZONYCH DANYCH");
        panel1.add(warning, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        errorLabel = new JLabel();
        errorLabel.setText("");
        panel1.add(errorLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        generationCountSpinner = new JSpinner(generationSpinnerModel);
        matchListCountSpinner = new JSpinner(matchListSpinnerModel);
        comparisonCountSpinner = new JSpinner(comparisonSpinnerModel);
    }
}
